name: shamo
description: A new
 Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  provider: ^6.1.2
  http: ^1.2.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins/
      # fonts:
      #   - asset: assets/fonts/Poppins-Regular.ttf
      #   - asset: assets/fonts/Poppins-Italic.ttf
      #     style: italic
      #   - asset: assets/fonts/Poppins-Bold.ttf
      #     weight: 700
